# Generated by Django 2.2.7 on 2020-01-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
